name: Releases

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true

      - run: cd node && npm install && npm build

      - run: cargo build --verbose --release

      - run: |
          mkdir dist
          tar -czvf dist/webnote-linux-amd64.tar.gz -C target/release webnote

      - uses: softprops/action-gh-release@v2
        if: ${{ github.event_name != 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
