name: Releases

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo build --verbose --release

      - run: |
          mkdir dist
          tar -czvf dist/webnote-linux-amd64.tar.gz target/release/webnote

      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
