name: Releases

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build
      run: make

    - name: Package
      run: |
        mkdir dist
        tar -czvf dist/webnote-linux-amd64.tar.gz webnote

    - name: Package Arch Linux
      run: |
        V=$(git describe --abbrev=0 --tags)
        sed -i s/pkgver=/pkgver=$V/ .pkg/PKGBUILD
        mv webnote .pkg
        docker build --output=dist/ .pkg

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/*
